services:

  postgres:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./backend:/app/backend
      - ./alembic.ini:/app/alembic.ini
      - ./backend/alembic:/app/backend/alembic
    command: alembic upgrade head
    restart: "no"
    profiles: ["migrate"]

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - backend
      - redis
      - postgres
    volumes:
      - ./backend:/app/backend
    command: celery -A tasks.worker worker --loglevel=info

volumes:
  pgdata:
